---
title: "neuRo reference book"
author: "Andreas Gammelgaard Damsbo"
date: "Last render: `r format(Sys.time(), format='%d.%b.%Y-%H:%M')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: agdamsbo/neuRo-group
description: "This is a reference book on introducing working in R and references for further research work in R. part of the neuRo-group at AUH, DK"
---

# Preamble {-}

This book started as collection of bookmarks for learning and working in R with health data as part of a R usergroup in our research group. It has evolved quite a bit, and can be seen as more of a handbook for the clinical researcher using [REDCap]() for data collection and R for data analysis.

## Content {-}

The book consists of several sections. The first part is concerned with recommendations for the new R-user to get started. The next section focuses on the use of REDCap, from getting access to data to building a database. Lastly the package `{stRoke}` is introduced, which is a small toolbox of collected tools for easier data management and analysis.

## The author {-}

This book was created and is maintained by Andreas G Damsbo ([GitHub](https://github.com/agdamsbo), [ORCiD](https://orcid.org/my-orcid?orcid=0000-0002-7559-1154)), clinical researcher and PhD-student at Aarhus University and Aarhus University Hospital working in clinical stroke research.

## Source {-}

This book and its content is open source and shared under the AGPL-3 license.

The source files are [hosted on GitHub](https://github.com/agdamsbo/neuRo-group). You are welcome to contribute through comments, PRs or you can write an [email](mailto:agdamsbo@clin.au.dk).

The book is build using the **bookdown** package[@R-bookdown] using the [**bookdown-demo**](https://github.com/rstudio/bookdown-demo).

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'REDCapR', 'tidyverse', 'stRoke', "REDCapRITS","keyring"
), 'packages.bib')
```
